<?php

namespace App\Console\Commands;

use App\Services\Local\LocalCommandRegistry;
use App\Services\Local\Platform\PlatformDetector;
use App\Services\Privilege\PrivilegedCommand;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * L9 deliverable: "a documented list of every shell command this module can
 * execute, per platform".
 *
 * Generated from LocalCommandRegistry for the same reason
 * docs/PRIVILEGED-COMMANDS.md is generated from CommandRegistry — a hand-written
 * list of what a program can do is a list of what it could do when somebody last
 * remembered to update it.
 */
class LocalCommandsCommand extends Command
{
    protected $signature = 'jetgrid:local-commands {--markdown : Write docs/LOCAL-MODE-COMMANDS.md}';

    protected $description = 'List every command local mode is capable of executing, grouped by platform.';

    /** Key prefix => the platform it runs on. Anything unlisted is cross-platform. */
    private const PLATFORMS = [
        'windows' => 'Windows',
        'macos' => 'macOS',
        'linux' => 'Linux',
        'unix' => 'macOS and Linux',
    ];

    public function handle(LocalCommandRegistry $registry, PlatformDetector $platform): int
    {
        if ($this->option('markdown')) {
            return $this->writeMarkdown($registry);
        }

        $this->components->info('Detected platform: '.$platform->family()->label());

        $this->table(
            ['Key', 'Platform', 'Write', 'Command'],
            collect($registry->all())
                ->map(fn (PrivilegedCommand $c): array => [
                    $c->key,
                    $this->platformFor($c->key),
                    $c->isWrite ? 'YES' : 'no',
                    implode(' ', $c->argv),
                ])
                ->values()
                ->all(),
        );

        $this->components->info(count($registry->all()).' commands total. Nothing outside this list can be executed in local mode.');

        return self::SUCCESS;
    }

    private function writeMarkdown(LocalCommandRegistry $registry): int
    {
        $lines = [
            '# Every shell command JetGrid local mode can execute',
            '',
            '> Generated by `php artisan jetgrid:local-commands --markdown` from',
            '> `App\Services\Local\LocalCommandRegistry`. Do not edit by hand.',
            '>',
            '> Generated: '.now()->toDateTimeString(),
            '',
            'This is the complete list. `LocalCommandRunner` refuses any key that is not',
            'here, every `{placeholder}` is validated against an exact pattern before the',
            'command is built, and arguments reach the process as an **array** — no shell,',
            'no string command line, so no argument value can introduce a second command.',
            '',
            '## Rules that apply to every command on this page',
            '',
            '- **Never run with sudo or as root.** Every entry has `needsRoot = false`, so',
            '  none of them appears in `artifacts/jetgrid-sudoers`.',
            '- **Never run unless the L0 gate passes.** All four checks — `jetgrid.mode`,',
            '  `APP_ENV`, the absence of a production marker file, and',
            '  `PlatformDetector::isLocalWorkstation()` — must pass, on reads as well as',
            '  writes.',
            '- **Never run inside a project directory in a way that writes to it.** A',
            '  project directory is used as a working directory and read from. The only',
            '  files local mode creates are under `storage/app/jetgrid/`.',
            '- **Write commands are audited.** An `audit_logs` row is opened before the',
            '  process starts and closed with its exit code, output and duration. Read',
            '  commands are not audited: the run-state probe issues several per project',
            '  every few seconds while a dashboard is open, and recording those would bury',
            '  the records that matter.',
            '- **A missing binary is not an error.** It degrades the layer that needed it.',
            '  `php artisan jetgrid:doctor` reports which tools are present and what stops',
            '  working without each one.',
            '',
        ];

        $groups = [];

        foreach ($registry->all() as $command) {
            $groups[$this->platformFor($command->key)][] = $command;
        }

        // Cross-platform first: it is the majority and the least surprising.
        uksort($groups, static fn (string $a, string $b): int => [$a === 'All platforms' ? 0 : 1, $a] <=> [$b === 'All platforms' ? 0 : 1, $b]);

        foreach ($groups as $platform => $commands) {
            $lines[] = '## '.$platform.' ('.count($commands).')';
            $lines[] = '';

            foreach ($commands as $command) {
                $lines[] = '### `'.$command->key.'`';
                $lines[] = '';
                $lines[] = '```';
                $lines[] = implode(' ', $command->argv);
                $lines[] = '```';
                $lines[] = '';
                $lines[] = '- **Changes something:** '.($command->isWrite ? 'yes — audited, and refused unless the gate passes' : 'no — read-only');
                $lines[] = '- **Why:** '.$command->justification;

                if ($command->patterns !== []) {
                    $lines[] = '- **Argument patterns:**';

                    foreach ($command->patterns as $name => $pattern) {
                        $lines[] = '  - `'.$name.'` — `'.$pattern.'`';
                    }
                }

                $lines[] = '';
            }
        }

        $lines[] = '## Commands local mode will never run';
        $lines[] = '';
        $lines[] = 'Listed because their absence is a design decision, not an oversight:';
        $lines[] = '';
        $lines[] = '- `composer install`, `npm install` and `php artisan migrate` exist in the';
        $lines[] = '  registry but are **never run automatically**. `ProcessController::maintenance()`';
        $lines[] = '  refuses them unless the caller echoes back the exact rendered command line.';
        $lines[] = '- No command writes into a discovered project directory.';
        $lines[] = '- No command is passed to a shell. `powershell -Command` is the one entry that';
        $lines[] = '  interpolates a value into a script, and that value is a PID constrained to';
        $lines[] = '  `'.LocalCommandRegistry::P_PID.'`.';
        $lines[] = '- Detached dev servers are spawned with `proc_open` and an argv array, not';
        $lines[] = '  Symfony Process: Process kills its child in its destructor, which would stop';
        $lines[] = '  every dev server the moment the request that started it ended.';
        $lines[] = '';

        $path = base_path('docs/LOCAL-MODE-COMMANDS.md');
        File::ensureDirectoryExists(dirname($path));
        File::put($path, implode("\n", $lines));

        $this->components->info('Wrote '.$path);

        return self::SUCCESS;
    }

    private function platformFor(string $key): string
    {
        $prefix = strtok($key, '.');

        return self::PLATFORMS[$prefix] ?? 'All platforms';
    }
}
