<?php

namespace App\Console\Commands;

use App\Services\Privilege\CommandRegistry;
use App\Services\Privilege\PrivilegedCommand;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Deliverable: "a written list of every privileged command JetGrid can execute".
 *
 * Generated from the registry rather than maintained by hand, so the document
 * cannot quietly fall out of step with the code.
 */
class PrivilegedCommandsCommand extends Command
{
    protected $signature = 'jetgrid:commands {--markdown : Write docs/PRIVILEGED-COMMANDS.md}';

    protected $description = 'List every command JetGrid is capable of executing.';

    public function handle(CommandRegistry $registry): int
    {
        if ($this->option('markdown')) {
            return $this->writeMarkdown($registry);
        }

        $this->table(
            ['Key', 'Root', 'Write', 'Command'],
            collect($registry->all())
                ->map(fn (PrivilegedCommand $c): array => [
                    $c->key,
                    $c->needsRoot ? 'yes' : 'no',
                    $c->isWrite ? 'YES' : 'no',
                    implode(' ', $c->argv),
                ])
                ->values()
                ->all(),
        );

        $this->components->info(count($registry->all()).' commands total. Nothing outside this list can be executed.');

        return self::SUCCESS;
    }

    private function writeMarkdown(CommandRegistry $registry): int
    {
        $lines = [
            '# Every privileged command JetGrid can execute',
            '',
            '> Generated by `php artisan jetgrid:commands --markdown` from',
            '> `App\Services\Privilege\CommandRegistry`. Do not edit by hand.',
            '>',
            '> Generated: '.now()->toDateTimeString(),
            '',
            'This is the complete list. `CommandRunner` refuses any key that is not here,',
            'and every `{placeholder}` is validated against an exact pattern before the',
            'command is built. Arguments are passed to the process as an **array**, never',
            'through a shell, so no argument value can introduce a second command.',
            '',
            '## How to read this',
            '',
            '- **Write** commands are refused entirely while `JETGRID_READONLY=true`, and',
            '  refused for adopted/protected resources in every mode.',
            '- **Read** commands run in every mode. Discovery and monitoring use only these.',
            '- **Root** indicates the command appears in the generated sudoers file.',
            '',
        ];

        foreach ([
            'Read-only commands' => $registry->reads(),
            'Write commands' => $registry->writes(),
        ] as $heading => $commands) {
            $lines[] = '## '.$heading.' ('.count($commands).')';
            $lines[] = '';

            foreach ($commands as $command) {
                $lines[] = '### `'.$command->key.'`';
                $lines[] = '';
                $lines[] = '```';
                $lines[] = implode(' ', $command->argv);
                $lines[] = '```';
                $lines[] = '';
                $lines[] = '- **Root:** '.($command->needsRoot ? 'yes (in sudoers)' : 'no');
                $lines[] = '- **Why:** '.$command->justification;

                if ($command->patterns !== []) {
                    $lines[] = '- **Argument patterns:**';

                    foreach ($command->patterns as $name => $pattern) {
                        $lines[] = '  - `'.$name.'` — `'.$pattern.'`';
                    }
                }

                $lines[] = '';
            }
        }

        $path = base_path('docs/PRIVILEGED-COMMANDS.md');
        File::ensureDirectoryExists(dirname($path));
        File::put($path, implode("\n", $lines));

        $this->components->info('Wrote '.$path);

        return self::SUCCESS;
    }
}
