<?php

namespace App\Console\Commands;

use App\Services\Privilege\CommandRegistry;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Safety constraint #3 — generate the sudoers whitelist as a reviewable artifact.
 *
 * It is written to artifacts/ and NOT installed. Installing it is a manual step
 * you take after reading it, because a control panel that installs its own sudo
 * rules is a control panel you have to trust rather than verify.
 */
class SudoersCommand extends Command
{
    protected $signature = 'jetgrid:sudoers {--output=artifacts/jetgrid-sudoers}';

    protected $description = 'Generate the sudoers whitelist for review. Does not install it.';

    public function handle(CommandRegistry $registry): int
    {
        $user = config('jetgrid.own_user');
        $lines = [];
        $broadCommands = [];

        $lines[] = '# ---------------------------------------------------------------------------';
        $lines[] = '# JetGrid sudoers whitelist';
        $lines[] = '#';
        $lines[] = '# GENERATED by `php artisan jetgrid:sudoers` from';
        $lines[] = '# App\Services\Privilege\CommandRegistry. Do not edit by hand — edit the';
        $lines[] = '# registry and regenerate, so the code and this file cannot disagree.';
        $lines[] = '#';
        $lines[] = '# Generated: '.now()->toDateTimeString();
        $lines[] = '#';
        $lines[] = '# REVIEW THIS FILE BEFORE INSTALLING IT. Every line grants one specific';
        $lines[] = '# command to the "'.$user.'" user with no password. There is deliberately no';
        $lines[] = '# NOPASSWD:ALL, and no shell, editor, package manager or interpreter here.';
        $lines[] = '#';
        $lines[] = '# A NOTE ON WILDCARDS, because it decides how much this file is worth:';
        $lines[] = '#   In sudoers, a wildcard in a command ARGUMENT matches that whole argument,';
        $lines[] = '#   slashes included. So `systemctl restart *` would permit';
        $lines[] = '#   `systemctl restart nginx`. This file therefore keeps literal prefixes';
        $lines[] = '#   (jetgrid-*) and expands small closed sets (tcp/udp, PHP versions) into';
        $lines[] = '#   explicit lines, so that these rules stay narrow even if the application';
        $lines[] = '#   layer above them is bypassed entirely.';
        $lines[] = '#';
        $lines[] = '# Install with:';
        $lines[] = '#   sudo visudo -cf jetgrid-sudoers        # validate FIRST';
        $lines[] = '#   sudo install -m 0440 -o root -g root jetgrid-sudoers /etc/sudoers.d/jetgrid';
        $lines[] = '#';
        $lines[] = '# Remove with:';
        $lines[] = '#   sudo rm /etc/sudoers.d/jetgrid';
        $lines[] = '# ---------------------------------------------------------------------------';
        $lines[] = '';
        $lines[] = 'Defaults:'.$user.' !requiretty';
        $lines[] = 'Defaults:'.$user.' env_reset';
        $lines[] = '';

        $reads = [];
        $writes = [];

        foreach ($registry->requiringRoot() as $command) {
            $patterns = $command->sudoersPatterns();

            if ($patterns === []) {
                continue;
            }

            $entry = ['# ['.$command->key.'] '.$command->justification];

            foreach ($command->broadArguments() as $name => $reason) {
                $entry[] = '#   BROAD ARGUMENT {'.$name.'}: '.$reason;
                $broadCommands[$command->key][$name] = $reason;
            }

            foreach ($patterns as $pattern) {
                $entry[] = $user.' ALL=(root) NOPASSWD: '.$pattern;
            }

            $entry[] = '';

            if ($command->isWrite) {
                $writes = array_merge($writes, $entry);
            } else {
                $reads = array_merge($reads, $entry);
            }
        }

        $lines[] = '# === READ-ONLY =============================================================';
        $lines[] = '# These are the only privileged commands JetGrid runs while';
        $lines[] = '# JETGRID_READONLY=true. Discovery and monitoring need nothing else, so a';
        $lines[] = '# monitoring-only install can stop after this section.';
        $lines[] = '';
        $lines = array_merge($lines, $reads);

        $lines[] = '# === WRITES ================================================================';
        $lines[] = '# Refused entirely by the application while JETGRID_READONLY=true, and';
        $lines[] = '# refused for adopted sites in every mode. For a strictly monitoring-only';
        $lines[] = '# install, DELETE this whole section: JetGrid degrades cleanly to read-only';
        $lines[] = '# and the write actions simply fail.';
        $lines[] = '';
        $lines = array_merge($lines, $writes);

        if ($broadCommands !== []) {
            $lines[] = '# === RESIDUAL RISK =========================================================';
            $lines[] = '# The rules below could not be narrowed by sudo alone. For these, the';
            $lines[] = '# restriction to JetGrid-managed resources exists ONLY in the application';
            $lines[] = '# layer (the protected gate, the policies and the argument patterns).';
            $lines[] = '# If that distinction matters to you, delete these specific lines and';
            $lines[] = '# perform those operations by hand:';
            $lines[] = '#';

            foreach ($broadCommands as $key => $arguments) {
                foreach ($arguments as $name => $reason) {
                    $lines[] = '#   ['.$key.'] {'.$name.'} — '.$reason;
                }
            }

            $lines[] = '';
        }

        $lines[] = '# === NOT GRANTED ===========================================================';
        $lines[] = '# For the avoidance of doubt, JetGrid never asks for and must never be given:';
        $lines[] = '#   - NOPASSWD: ALL';
        $lines[] = '#   - any shell (sh, bash), interpreter (php, python, perl) or editor';
        $lines[] = '#   - package management (apt-get install, dpkg)';
        $lines[] = '#   - unrestricted systemctl (only the jetgrid-* units and nginx reload)';
        $lines[] = '#   - bare `certbot renew` (it would sweep up your adopted certificates)';
        $lines[] = '#   - chown/chmod/rm outside the jetgrid-prefixed paths above';
        $lines[] = '';

        $path = base_path($this->option('output'));
        File::ensureDirectoryExists(dirname($path));
        File::put($path, implode("\n", $lines));

        $this->components->info('Wrote '.$path);
        $this->components->twoColumnDetail('Read-only commands', (string) count($registry->reads()));
        $this->components->twoColumnDetail('Write commands', (string) count($registry->writes()));
        $this->components->twoColumnDetail('Requiring root', (string) count($registry->requiringRoot()));
        $this->components->twoColumnDetail('Unprivileged', (string) count($registry->unprivileged()));
        $this->components->twoColumnDetail(
            $broadCommands === [] ? 'Broad rules' : '<fg=yellow>Broad rules</>',
            (string) count($broadCommands),
        );
        $this->newLine();
        $this->components->warn('Not installed. Read it — especially the RESIDUAL RISK section — then install it yourself.');

        return self::SUCCESS;
    }
}
